exclude: (\.mywaflib)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: debug-statements
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.0
    hooks:
    -   id: reorder-python-imports
        files: '(\.pyi?|wscript)$'
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      files: '(\.py|wscript)$'
      additional_dependencies: [
        flake8-bugbear, flake8-builtins, flake8-comprehensions, flake8-deprecated,
        flake8-docstrings, flake8-eradicate, flake8-print, flake8-rst-docstrings,
        flake8-todo, pep8-naming, pydocstyle==3.0.0,
      ]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.2.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black]
        types: [rst]
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
        files: '(\.pyi?|wscript)$'
-   repo: local
    hooks:
    - id: doc8
      entry: doc8
      language: system
      types: [rst]
      name: doc8 - Lint the documentation.
    - id: restructuredtext-lint
      entry: rst-lint
      language: system
      files: '(README.rst)'
      name: restructuredtext-lint - Is the README PyPi-compliant?
-   repo: meta
    hooks:
    # -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.