def build(ctx):
    ctx.recurse('data_management')
    ctx.recurse('analysis')
    ctx.recurse('figures')
    # Safety measure -- else the LaTeX scanner might fail because some
    # '.tex'-source file has not been generated.
    ctx.add_group()
    ctx.recurse('paper')
    ctx.recurse('documentation')

    from src.figures.project_dependency_graph import (
        make_project_dependency_graph
    )

    ctx.add_post_fun(make_project_dependency_graph)
