def build(ctx):

    ctx(
        features="run_py_script",
        source="get_simulation_draws.py",
        target=ctx.path_to(ctx, "OUT_DATA", "initial_locations.csv"),
        name="get_simulation_draws",
    )

    ctx(rule="pytest ../src/data_management --no-cov", name="test_data_management")
